// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAue53ruE1Yk5OXL_8oBF5m2UjWnF2u0Aw',
    appId: '1:233812163402:web:674663179f06c0e9839fb3',
    messagingSenderId: '233812163402',
    projectId: 'fir-basic-60131',
    authDomain: 'fir-basic-60131.firebaseapp.com',
    storageBucket: 'fir-basic-60131.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmFqo8Rh8WCWyCb7LnjQ1A1TZpsXV99hY',
    appId: '1:233812163402:android:6a5281e851da8fbb839fb3',
    messagingSenderId: '233812163402',
    projectId: 'fir-basic-60131',
    storageBucket: 'fir-basic-60131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh6sl_eLTgzwsqK685x3sRmtvPWwfLa-0',
    appId: '1:233812163402:ios:746a4c20d5b90458839fb3',
    messagingSenderId: '233812163402',
    projectId: 'fir-basic-60131',
    storageBucket: 'fir-basic-60131.appspot.com',
    iosClientId: '233812163402-556us0mc23s2na55v1of4aoemv6nqkqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh6sl_eLTgzwsqK685x3sRmtvPWwfLa-0',
    appId: '1:233812163402:ios:746a4c20d5b90458839fb3',
    messagingSenderId: '233812163402',
    projectId: 'fir-basic-60131',
    storageBucket: 'fir-basic-60131.appspot.com',
    iosClientId: '233812163402-556us0mc23s2na55v1of4aoemv6nqkqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
